monolog:
    handlers:
        file:
          type: rotating_file
          path: '%kernel.logs_dir%/%kernel.environment%.log'
          level: info
        stdout:
            type: stream
            level: info
            path: 'php://stdout'
        main:
          type: rotating_file
          path: '%kernel.logs_dir%/%kernel.environment%.log'
          level: info