version: "3.4"

# Production environment override
services:
  php:
    environment:
      APP_SECRET: ${APP_SECRET}

  nginx:
    networks:
      web:
    # add labels like traefik proxy conf
    labels:
      - 'traefik.enable=true'

  database:
    # expose db port on localhost
    ports:
      - '127.0.0.1:3306:3306'

# whoami can be used to test traefik
#  whoami:
#    image: traefik/whoami:v1.8.1
#    networks:
#      - web
#    labels:
#      - 'traefik.enable=true'
#      - 'traefik.http.routers.whoami.tls=true'
#      - 'traefik.http.routers.whoami.entrypoints=websecure'
#      - 'traefik.http.routers.whoami.rule=Host(`example.com`)'
#      - 'traefik.http.services.whoami.loadbalancer.server.port=80'

# use existing networks
networks:
  web:
    external: true
